pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_010_tensor_truediv
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_011_tensor_div
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_012_torch_pow
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_013_tensor_reciprocal
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_014_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_015_tensor_clone
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_044_tensor_copy
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_052_torch_isin
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_053_tensor_any
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_054_tensor_lt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_055_tensor_cumsum
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_056_tensor_sub
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_057_tensor_eq
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_058_tensor_masked_fill
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_059_torch_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_059_torch_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_060_torch_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_061_tensor_cumsum
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_062_tensor_sub
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_064_tensor_clone
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_065_torch_embedding
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_066_torch_arange
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_067_torch_arange
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_068_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_074_tensor_le
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_075_tensor_and
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_086_tensor_and
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_088_torch_where
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_092_tensor_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_094_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_095_tensor_cos
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_096_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_097_tensor_sin
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_098_tensor_pow
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_099_tensor_mean
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_100_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_101_torch_rsqrt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_102_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_103_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_104_torch_nn_functional_linear #fail sine bfloat16 cpu and gpu unequal
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_107_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_111_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_114_tensor_neg
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_115_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_116_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_117_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_118_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_121_tensor_neg
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_122_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_123_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_124_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_125_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_130_torch_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_131_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_132_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_133_tensor_softmax
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_134_torch_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_139_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_140_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_141_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_142_torch_nn_functional_silu
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_143_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_144_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_146_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_147_torch_arange
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_150_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_151_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_152_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_153_tensor_new_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_155_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_156_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_157_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_159_torch_gather
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_160_tensor_lt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_161_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_162_tensor_truediv
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_163_torch_where
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_164_tensor_scatter
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_165_tensor_truediv
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_166_torch_topk
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_168_tensor_lt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_169_torch_sort
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_170_tensor_softmax
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_171_tensor_cumsum
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_172_tensor_le
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_173_tensor_setitem
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_174_tensor_scatter
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_175_tensor_softmax
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_176_torch_multinomial
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_178_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_179_tensor_rsub
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_180_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_181_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_183_torch_full
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_184_tensor_or
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_186_torch_isin
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_187_tensor_invert
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_188_tensor_and
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_189_tensor_max
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_190_tensor_eq
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_192_tensor_clone
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_195_tensor_clone
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_196_torch_embedding
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_197_torch_arange
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_198_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_201_tensor_new_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_202_tensor_le
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_203_tensor_and
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_209_tensor_and
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_211_torch_where
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_213_tensor_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_215_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_216_tensor_cos
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_217_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_218_tensor_sin
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_219_tensor_pow
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_220_tensor_mean
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_221_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_222_torch_rsqrt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_223_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_224_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_225_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_228_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_232_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_235_tensor_neg
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_236_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_237_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_238_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_239_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_242_tensor_neg
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_243_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_244_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_245_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_246_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_247_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_252_torch_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_253_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_254_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_255_tensor_softmax
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_256_torch_matmul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_261_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_262_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_263_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_264_torch_nn_functional_silu
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_265_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_266_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_268_torch_nn_functional_linear
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_269_tensor_add
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_270_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_271_tensor_new_ones
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_273_torch_cat
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_274_torch_gather
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_275_tensor_lt
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_276_tensor_mul
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_277_tensor_truediv
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_278_torch_where
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_279_tensor_scatter
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_280_torch_full
pytest -v -s test_ops_qwen.py::TestOpsAuto::test_auto_282_torch_isin
