#!/bin/bash
# Auto-generated: 234 test cases

pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_001_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_002_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_003_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_004_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_005_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_006_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_007_torch_empty
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_008_torch_ones
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_009_torch_arange
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_010_tensor_truediv
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_011_tensor_div
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_012_torch_pow
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_013_tensor_reciprocal
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_014_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_015_tensor_clone
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_016_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_017_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_018_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_019_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_020_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_021_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_022_tensor_detach
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_023_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_024_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_025_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_026_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_027_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_028_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_029_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_030_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_031_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_032_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_033_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_034_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_035_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_036_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_037_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_038_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_039_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_040_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_041_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_042_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_043_torch_empty_like
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_044_tensor_copy
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_045_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_046_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_047_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_048_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_049_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_050_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_051_torch_has_compatible_shallow_copy_type
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_052_torch_isin
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_053_tensor_any
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_054_tensor_lt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_055_tensor_cumsum
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_056_tensor_sub
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_057_tensor_eq
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_058_tensor_masked_fill
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_059_torch_ones
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_060_torch_ones
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_061_tensor_cumsum
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_062_tensor_sub
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_063_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_064_tensor_clone
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_065_torch_nn_functional_embedding
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_066_torch_embedding
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_067_tensor_all
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_068_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_069_tensor_expand
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_070_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_071_tensor_matmul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_072_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_073_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_074_tensor_cos
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_075_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_076_tensor_sin
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_077_tensor_pow
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_078_tensor_mean
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_079_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_080_torch_rsqrt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_081_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_082_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_083_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_084_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_085_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_086_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_087_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_088_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_089_tensor_unsqueeze
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_090_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_091_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_092_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_093_tensor_neg
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_094_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_095_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_096_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_097_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_098_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_099_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_100_tensor_neg
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_101_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_102_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_103_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_104_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_105_torch_nn_functional_scaled_dot_product_attention
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_106_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_107_tensor_contiguous
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_108_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_109_tensor_contiguous
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_110_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_111_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_112_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_113_torch_nn_functional_silu
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_114_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_115_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_116_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_117_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_118_torch_arange
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_119_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_120_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_121_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_122_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_123_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_124_tensor_new_ones
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_125_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_126_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_127_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_128_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_129_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_130_torch_gather
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_131_tensor_lt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_132_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_133_tensor_truediv
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_134_torch_where
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_135_tensor_scatter
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_136_tensor_truediv
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_137_torch_topk
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_138_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_139_tensor_lt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_140_torch_sort
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_141_tensor_softmax
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_142_tensor_cumsum
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_143_tensor_le
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_144_tensor_setitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_145_tensor_scatter
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_146_torch_nn_functional_softmax
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_147_tensor_softmax
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_148_torch_multinomial
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_149_tensor_squeeze
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_150_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_151_tensor_rsub
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_152_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_153_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_154_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_155_torch_full
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_156_tensor_or
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_157_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_158_torch_isin
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_159_tensor_invert
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_160_tensor_and
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_161_tensor_max
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_162_tensor_eq
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_163_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_164_tensor_clone
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_165_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_166_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_167_tensor_clone
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_168_torch_nn_functional_embedding
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_169_torch_embedding
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_170_tensor_all
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_171_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_172_tensor_matmul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_173_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_174_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_175_tensor_cos
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_176_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_177_tensor_sin
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_178_tensor_pow
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_179_tensor_mean
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_180_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_181_torch_rsqrt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_182_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_183_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_184_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_185_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_186_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_187_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_188_tensor_view
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_189_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_190_tensor_unsqueeze
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_191_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_192_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_193_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_194_tensor_neg
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_195_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_196_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_197_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_198_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_199_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_200_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_201_tensor_neg
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_202_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_203_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_204_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_205_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_206_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_207_torch_nn_functional_scaled_dot_product_attention
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_208_tensor_transpose
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_209_tensor_contiguous
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_210_tensor_reshape
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_211_tensor_contiguous
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_212_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_213_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_214_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_215_torch_nn_functional_silu
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_216_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_217_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_218_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_219_torch_nn_functional_linear
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_220_tensor_add
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_221_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_222_tensor_new_ones
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_223_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_224_torch_cat
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_225_torch_gather
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_226_tensor_lt
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_227_tensor_mul
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_228_tensor_truediv
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_229_torch_where
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_230_tensor_scatter
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_231_torch_full
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_232_tensor_getitem
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_233_torch_isin
pytest -v -s test_ops_auto_res.py::TestOpsAuto::test_auto_234_tensor_getitem
